# Generated by Django 4.2.3 on 2023-07-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='small_desc',
            field=models.TextField(default='No Description.', max_length=35),
        ),
    ]
