# Generated by Django 4.2.3 on 2023-07-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipeingredientintermediary', '0001_initial'),
        ('recipeingredient', '0001_initial'),
        ('recipe', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(through='recipeingredientintermediary.RecipeIngredientIntermediary', to='recipeingredient.recipeingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='user.user'),
        ),
    ]
