# Generated by Django 4.2.3 on 2023-07-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeingredient', '0003_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount_type',
            field=models.CharField(choices=[('cup', 'Cup'), ('teaspoon', 'Teaspoon'), ('tablespoon', 'Tablespoon'), ('fluid ounce', 'Fluid Ounce'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon'), ('milliliter', 'Milliliter'), ('liter', 'Liter'), ('ounce', 'Ounce'), ('pound', 'Pound'), ('gram', 'Gram'), ('kilogram', 'Kilogram'), ('each', 'Each'), ('other', 'Other')], max_length=100),
        ),
    ]
